---
- hosts: agent
  tasks:
   - name: Installing nginx server
     apt: package=nginx state=present update_cache=yes
     notify:
      - start: start nginx
  handlers:
   - name: start nginx
     service: name=nginx state=started
